FROM python:3.13-slim

RUN useradd -m -s /bin/bash cats-migration

WORKDIR /app

COPY ../../requirements.txt /app/requirements.txt

RUN pip install --no-cache -r requirements.txt

COPY src/ /app/src/
COPY alembic.ini /app/alembic.ini
COPY .dockerignore /app/.dockerignore

RUN chown -R cats-migration:cats-migration /app/src/infra/database/migrations
USER cats-migration

ENV PYTHONPATH=/app

ENTRYPOINT ["alembic"]
CMD ["upgrade", "head"]
